### ISSUE TITLE
In the test mode, why are the network outputs the same?

### ISSUE THREAD

**Issue by WEIZHIHONG720** [xuyu0010/ARID_UG2_2.1#2]
Hello！Sorry to bother you！In the predict mode, why are the network outputs the same? 

The first picture is the data input into the network. You can see that it is different. But the output of the network is the same, as shown in the second picture. What's going on?

![3bbc2e7546821d5f2bf3981bb5bcedb](https://user-images.githubusercontent.com/43931281/154940465-122ec5eb-1b88-4edb-9d45-febbe7825c45.png)

**Comment by xuyu0010** [comment]
Hi, thank you for your interest, this should be the problem of ur network. It is a very complex question and cannot be explained in short. Your network, data processing all would impact your output.

**Comment by WEIZHIHONG720** [comment]
Sorry, issue should be submitted in [ARID_UG2_2.2] ，I submitted it in the wrong place.
